addpath(genpath('C:\Users\Daisy\Desktop\yalefaces'));
%subject14 
clear s1; ds = 4;
tmp = imread('subject14.gif'); tmp = tmp(1:ds:240,1:ds:end);
s1(1,:) = tmp(:)';
tmp = imread('subject14.glasses.gif');tmp = tmp(1:ds:240,1:ds:end);
s1(2,:) = tmp(:)';
tmp = imread('subject14.happy.gif');tmp = tmp(1:ds:240,1:ds:end);
s1(3,:) = tmp(:)';
tmp = imread('subject14.leftlight.gif');tmp = tmp(1:ds:240,1:ds:end);
s1(4,:) = tmp(:)';
tmp = imread('subject14.noglasses.gif');tmp = tmp(1:ds:240,1:ds:end);
s1(5,:) = tmp(:)';
tmp = imread('subject14.normal.gif');tmp = tmp(1:ds:240,1:ds:end);
s1(6,:) = tmp(:)';
tmp = imread('subject14.rightlight.gif');tmp = tmp(1:ds:240,1:ds:end);
s1(7,:) = tmp(:)';
tmp = imread('subject14.sad.gif');tmp = tmp(1:ds:240,1:ds:end);
s1(8,:) = tmp(:)';
tmp = imread('subject14.sleepy.gif');tmp = tmp(1:ds:240,1:ds:end);
s1(9,:) = tmp(:)';
tmp = imread('subject14.wink.gif');tmp = tmp(1:ds:240,1:ds:end);
s1(10,:) = tmp(:)';
mean_face = mean(s1);
s1 = double(s1); mean_face = mean(s1);
s1_zero = (s1-repmat(mean_face,10,1));
A = s1_zero'*s1_zero;
[V, D] = eigs(A);
%subject01
clear s2; ds = 4;
tmp = imread('subject01.gif'); tmp = tmp(1:ds:240,1:ds:end);
s2(1,:) = tmp(:)';
tmp = imread('subject01.glasses.gif');tmp = tmp(1:ds:240,1:ds:end);
s2(2,:) = tmp(:)';
tmp = imread('subject01.happy.gif');tmp = tmp(1:ds:240,1:ds:end);
s2(3,:) = tmp(:)';
tmp = imread('subject01.leftlight.gif');tmp = tmp(1:ds:240,1:ds:end);
s2(4,:) = tmp(:)';
tmp = imread('subject01.noglasses.gif');tmp = tmp(1:ds:240,1:ds:end);
s2(5,:) = tmp(:)';
tmp = imread('subject01.normal.gif');tmp = tmp(1:ds:240,1:ds:end);
s2(6,:) = tmp(:)';
tmp = imread('subject01.rightlight.gif');tmp = tmp(1:ds:240,1:ds:end);
s2(7,:) = tmp(:)';
tmp = imread('subject01.sad.gif');tmp = tmp(1:ds:240,1:ds:end);
s2(8,:) = tmp(:)';
tmp = imread('subject01.sleepy.gif');tmp = tmp(1:ds:240,1:ds:end);
s2(9,:) = tmp(:)';
tmp = imread('subject01.surprised.gif');tmp = tmp(1:ds:240,1:ds:end);
s2(10,:) = tmp(:)';
tmp = imread('subject01.wink.gif');tmp = tmp(1:ds:240,1:ds:end);
s2(11,:) = tmp(:)';
mean_face_1 = mean(s2);
s2 = double(s2); 
mean_face_1 = mean(s2);
s2_zero = (s2-repmat(mean_face_1,11,1));
B = s2_zero'*s2_zero;
[V_1, D_1] = eigs(B);
test=imread('subject14.test.gif');
test = test(1:ds:240,1:ds:end);
test=test(:)';
test=double(test);
[M,I]=max([test*V(:,1),test*V_1(:,1)]);